version: '3.8'

services:
  negotiation-agent:
    container_name: email-automation
    image: email-automation:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env  # optional, your other env variables
    environment:
      REDIS_HOST: services.supertruck.ai
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      RABBITMQ_HOST: services.supertruck.ai
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: 
      RABBITMQ_PASSWORD: 
      RABBITMQ_QUEUE: email_ingestion_queue
    network_mode: host
    restart: unless-stopped
    # volumes:
    #   - ./src:/app/src
